# This is simple servlet container based on the Apache Tomcat software
FROM tomcat:latest

COPY war/08-spring-boot-web-1.0-SNAPSHOT.war /usr/local/tomcat/webapps/08-spring.war

CMD ["catalina.sh", "run"]