version: '3'

services:
    web:
        image: httpd
        ports:
            - 9001:80
        depends_on:
            - db
        restart: always
    db:
        image: mariadb
        environment: 
            MYSQL_ROOT_PASSWORD: "xyz"

