
package pl.pg.asobecki.wai.jaxws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FirstWebServiceImplService", targetNamespace = "http://jaxws.wai.asobecki.pg.pl/", wsdlLocation = "http://localhost:8080/jax-ws/first-ws?wsdl")
public class FirstWebServiceImplService
    extends Service
{

    private final static URL FIRSTWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException FIRSTWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName FIRSTWEBSERVICEIMPLSERVICE_QNAME = new QName("http://jaxws.wai.asobecki.pg.pl/", "FirstWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/jax-ws/first-ws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FIRSTWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        FIRSTWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public FirstWebServiceImplService() {
        super(__getWsdlLocation(), FIRSTWEBSERVICEIMPLSERVICE_QNAME);
    }

    public FirstWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FIRSTWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public FirstWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, FIRSTWEBSERVICEIMPLSERVICE_QNAME);
    }

    public FirstWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FIRSTWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public FirstWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FirstWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FirstWebService
     */
    @WebEndpoint(name = "FirstWebServiceImplPort")
    public FirstWebService getFirstWebServiceImplPort() {
        return super.getPort(new QName("http://jaxws.wai.asobecki.pg.pl/", "FirstWebServiceImplPort"), FirstWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FirstWebService
     */
    @WebEndpoint(name = "FirstWebServiceImplPort")
    public FirstWebService getFirstWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jaxws.wai.asobecki.pg.pl/", "FirstWebServiceImplPort"), FirstWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FIRSTWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw FIRSTWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return FIRSTWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
