
package pl.pg.asobecki.wai.jaxws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FirstWebService", targetNamespace = "http://jaxws.wai.asobecki.pg.pl/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface FirstWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://jaxws.wai.asobecki.pg.pl/FirstWebService/getFirstWebServiceAsStringRequest", output = "http://jaxws.wai.asobecki.pg.pl/FirstWebService/getFirstWebServiceAsStringResponse")
    public String getFirstWebServiceAsString(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
